#!/bin/bash
#
# check that the PATH is checked in the right order

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH=":$PATH"
# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "cisfun" ]; then
    print_ok
    i=`expr $i + 1`
else
    print_ko
    j=`expr $j + 1`
fi

# clean up
stop_shell
$RM -f $tmp_file
